### ISSUE TITLE
Issue with "Regenerate Response" Button Deleting Previous AI-Generated Messages

### ISSUE THREAD

**Issue by Federico-German** [Leniolabs/promptree#1]
Description: When using the "Regenerate Response" button, the last message generated by the AI is deleted from the screen, but the button remains clickable. Upon subsequent clicks, the button continues to delete all previous AI-generated messages from the screen. However, when the final regenerated message appears, all previous messages are restored, and only the last one changes.

Steps to reproduce:

Start a conversation with the AI and generate multiple responses.
Click the "Regenerate Response" button once to regenerate a new message.
Notice that the last generated message disappears from the screen, but the button remains clickable.
Click the "Regenerate Response" button again.
Notice that all previous AI-generated messages disappear from the screen.
Repeat step 4 several times to see that the button continues to delete previous messages.
Wait for the final regenerated message to appear.
Notice that all previous messages are restored, and only the last one changes.
Expected behavior:
The "Regenerate Response" button should only delete the last generated message and replace it with a new one. Previous messages should remain on the screen.

Actual behavior:
The "Regenerate Response" button deletes previous AI-generated messages from the screen, causing confusion for users who may want to refer back to previous messages.

**Comment by apresmoi** [comment]
Thanks for the report, currently we do not have any safeguards for any subsequen presses of the regenerate button. We should probably disable the button while it's processing a new response and also add some kind of loading to show that the AI is currently generating the response.

**Comment by apresmoi** [comment]
This has been solved in the latest commits, it will be deployed soon.

Thank you!
