### ISSUE TITLE
Issue with Editing Chat Title - Enter Key Not Confirming Changes

### ISSUE THREAD

**Issue by Federico-German** [Leniolabs/promptree#2]
Description: When editing the chat title, pressing the Enter key does not confirm the changes made. The user is required to click the tick icon in order to confirm and save the changes.

Steps to reproduce:

Navigate to the chat title  section.
Click the pencil of the chat to edit.
Type a new title for the chat.
Press the Enter key on the keyboard.
Expected behavior:
Pressing the Enter key should confirm and save the changes made to the chat title.

Actual behavior:
Pressing the Enter key does not confirm and save the changes made to the chat title. The user is required to click the tick icon in order to save the changes.

Impact:
This issue may cause frustration and confusion for users who are accustomed to using the Enter key to confirm changes. It may also lead to users forgetting to click the tick icon, resulting in their changes not being saved.

Possible solution:
To improve the user experience, the Enter key should be programmed to confirm and save changes made to the chat title.

**Comment by apresmoi** [comment]
Thanks for the report ! I believe do not have any kindof key detection when you press enter there. We can add that.

**Comment by apresmoi** [comment]
Solved by #3
